# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: after
#   annotations:
#     argocd.argoproj.io/hook: PostSync
#     # argocd.argoproj.io/hook-delete-policy: HookSucceeded
# spec:
#   template:
#     spec:
#       containers:
#       - name: sleep
#         image: alpine:latest
#         command: ["sleep", "10"]
#       restartPolicy: Never
#   backoffLimit: 0
apiVersion: batch/v1
kind: Job
metadata:
  generateName: solr-config-collection-creator
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: solr-configurator
          image: 652646727745.dkr.ecr.us-east-1.amazonaws.com/disqoversolrbootstrapper:1.0.0
          env:
            - name: URL
              value: "http://write-solr-cluster.svc.cluster.local"
      restartPolicy: Never
      imagePullSecrets:
        - name: aws-registry
  backoffLimit: 2
