apiVersion: batch/v1
kind: Job
metadata:
  name: disqover-solr-configurator
  annotations:
    argocd.argoproj.io/hook:  PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: solr-configurator
          image: {{ .Values.configurationimage }}
          env:
            - name: URL
              value: "http://{{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local"
      restartPolicy: Never
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}
  backoffLimit: 0
