apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  name: solr-prometheus-exporter
spec:
  customKubeOptions:
    podOptions:
      resources:
        requests:
          cpu: 300m
          memory: 900Mi
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: solr
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
  solrReference:
    cloud:
      name: {{ .Values.name }}
  numThreads: 6